services:
  db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe 
    ports:
      - "1521:1521"
    environment:
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - DB_USER=evelyn
      - DB_PASSWORD=oracle123
    volumes:
      - oracle-volume:/opt/oracle/oradata
      - ./oracle-init:/container-entrypoint-initdb.d:ro
volumes:
  oracle-volume: