ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
   FOR t IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;


CREATE TABLE CENTRO_EVALUACION (
  ID_CENTRO NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  DIRECCION VARCHAR2(200)
);
