ALTER SESSION SET CONTAINER = XEPDB1;


-- TABLAS DE UBICACIÓN

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CODIGO NUMBER
);

CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DEPARTAMENTO_ID NUMBER,
    CONSTRAINT FK_MUNICIPIO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);


-- CENTROS DE EVALUACIÓN
 CREATE TABLE CENTRO_EVALUACION (
    ID_CENTRO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(200)
);


-- ESCUELAS

CREATE TABLE ESCUELA (
    ID_ESCUELA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(200),
    ACUERDO VARCHAR2(50)
);

-- Tabla intermedia para relacionar ESCUELAS y CENTROS (muchos a muchos)
CREATE TABLE ESCUELA_CENTRO (
    ESCUELA_ID NUMBER,
    CENTRO_ID NUMBER,
    PRIMARY KEY (ESCUELA_ID, CENTRO_ID),
    CONSTRAINT FK_ESCUELA_CENTRO_ESC FOREIGN KEY (ESCUELA_ID)
        REFERENCES ESCUELA(ID_ESCUELA),
    CONSTRAINT FK_ESCUELA_CENTRO_CENT FOREIGN KEY (CENTRO_ID)
        REFERENCES CENTRO_EVALUACION(ID_CENTRO)
);


-- PERSONAS

CREATE TABLE PERSONA (
    ID_REGISTRO NUMBER PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR2(150),
    DIRECCION VARCHAR2(200),
    IDENTIFICACION VARCHAR2(20),
    TELEFONO VARCHAR2(20),
    FOTO BLOB,
    TIPO_LICENCIA CHAR(1),  -- M, P, B, A, E
    TIPO_TRAMITE VARCHAR2(20), -- PRIMER_LICENCIA, TRASPASO
    GENERO CHAR(1),
    FECHA DATE,  -- FECHA DEL REGISTRO / EVALUACIÓN
    UBICACION_ESCUELA_ID_ESCUELA NUMBER,
    UBICACION_CENTRO_ID_CENTRO NUMBER,
    MUNICIPIO_ID_MUNICIPIO NUMBER,
    MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER,
    CONSTRAINT FK_PERSONA_MUNICIPIO FOREIGN KEY (MUNICIPIO_ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID_MUNICIPIO),
    CONSTRAINT FK_PERSONA_DEPARTAMENTO FOREIGN KEY (MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT FK_PERSONA_ESC FOREIGN KEY (UBICACION_ESCUELA_ID_ESCUELA)
        REFERENCES ESCUELA(ID_ESCUELA),
    CONSTRAINT FK_PERSONA_CENTRO FOREIGN KEY (UBICACION_CENTRO_ID_CENTRO)
        REFERENCES CENTRO_EVALUACION(ID_CENTRO)
);


-- CORRELATIVO DIARIO DE EXÁMENES

CREATE TABLE CORRELATIVO (
    ID_CORRELATIVO NUMBER PRIMARY KEY,
    FECHA DATE,
    NO_EXAMEN NUMBER
);

-- EXAMENES


CREATE TABLE EXAMEN (
    ID_EXAMEN NUMBER PRIMARY KEY,
    REGISTRO_ID_ESCUELA NUMBER,
    REGISTRO_ID_CENTRO NUMBER,
    REGISTRO_MUNICIPIO_ID_MUNICIPIO NUMBER,
    REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER,
    REGISTRO_ID_REGISTRO NUMBER,
    CORRELATIVO_ID_CORRELATIVO NUMBER,
    CONSTRAINT FK_EXAMEN_ESCUELA FOREIGN KEY (REGISTRO_ID_ESCUELA)
        REFERENCES ESCUELA(ID_ESCUELA),
    CONSTRAINT FK_EXAMEN_CENTRO FOREIGN KEY (REGISTRO_ID_CENTRO)
        REFERENCES CENTRO_EVALUACION(ID_CENTRO),
    CONSTRAINT FK_EXAMEN_MUNICIPIO FOREIGN KEY (REGISTRO_MUNICIPIO_ID_MUNICIPIO)
        REFERENCES MUNICIPIO(ID_MUNICIPIO),
    CONSTRAINT FK_EXAMEN_DEPARTAMENTO FOREIGN KEY (REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT FK_EXAMEN_PERSONA FOREIGN KEY (REGISTRO_ID_REGISTRO)
        REFERENCES PERSONA(ID_REGISTRO),
    CONSTRAINT FK_EXAMEN_CORRELATIVO FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO)
        REFERENCES CORRELATIVO(ID_CORRELATIVO)
);


-- PREGUNTAS TEÓRICAS

CREATE TABLE PREGUNTA_TEORICA (
    ID_PREGUNTA NUMBER PRIMARY KEY,
    PREGUNTA_TEXTO VARCHAR2(500),
    RESPUESTA_CORRECTA NUMBER, -- 1 a 4
    RES1 VARCHAR2(200),
    RES2 VARCHAR2(200),
    RES3 VARCHAR2(200),
    RES4 VARCHAR2(200),
    IMAGEN BLOB
);

-- RESPUESTAS TEÓRICAS POR EXAMEN

CREATE TABLE RESPUESTA_USUARIO (
    ID_RESPUESTA NUMBER PRIMARY KEY,
    PREGUNTA_ID NUMBER,
    EXAMEN_ID NUMBER,
    RESPUESTA NUMBER,
    CONSTRAINT FK_RESPUESTA_PREGUNTA FOREIGN KEY (PREGUNTA_ID)
        REFERENCES PREGUNTA_TEORICA(ID_PREGUNTA),
    CONSTRAINT FK_RESPUESTA_EXAMEN FOREIGN KEY (EXAMEN_ID)
        REFERENCES EXAMEN(ID_EXAMEN)
);

-- PREGUNTAS PRÁCTICAS

CREATE TABLE PREGUNTA_PRACTICA (
    ID_PREGUNTA_PRACTICA NUMBER PRIMARY KEY,
    PREGUNTA_TEXTO VARCHAR2(500),
    PUNTEO NUMBER
);


-- RESPUESTAS PRÁCTICAS POR EXAMEN

CREATE TABLE RESPUESTA_PRACTICO (
    ID_RESPUESTA_PRACTICO NUMBER PRIMARY KEY,
    PREGUNTA_PRACTICA_ID NUMBER,
    EXAMEN_ID NUMBER,
    NOTA NUMBER,
    CONSTRAINT FK_RESP_PRACTICO_PREGUNTA FOREIGN KEY (PREGUNTA_PRACTICA_ID)
        REFERENCES PREGUNTA_PRACTICA(ID_PREGUNTA_PRACTICA),
    CONSTRAINT FK_RESP_PRACTICO_EXAMEN FOREIGN KEY (EXAMEN_ID)
        REFERENCES EXAMEN(ID_EXAMEN)
);